Update README.md
gbaranski/gbaranski pull request #1
Opened 2022-02-17 12:46 UTC by gbaranski

2022-02-17 12:49 UTC, gbaranski commented
Hi @stanbar, given your enormously high level of knowledge about the English language, could you do me a favour by reviewing the text for possible mistakes?

Thanks in advance - I appreciate your help!

2022-02-17 13:16 UTC, stanbar requested changes

2022-02-17 13:16 UTC, stanbar commented on README.md
> +My experience is mostly with networking and system programming, however some projects required me to also code some frontend app or do something on microcontrollers like STM32 or ESP8266. And I like
```suggestion
My experience is mostly with dev/ops, networking and system programming. Also, I'm familiar with low-level and frontend development since some projects involved microcontrollers (STM32 or ESP8266) and required me to build a user interface. 
I enjoy experimenting and trying new things.
```

2022-02-17 13:16 UTC, stanbar commented on README.md
> +I'm pretty fluent with Rust, moreover languages like Go or Typescript aren't foreign to me.
```suggestion
I'm fluent with Rust, less with Go and Typescript.
```

2022-02-17 13:16 UTC, stanbar commented on README.md
> +It's essential for me to have a large toolbox, so I can pick the best tool for the problem, and since I was working as a one-man army for most of my projects, I needed a lot of different tools.
```suggestion
Before I get my hands dirty and jump to programming, I like to research and find the most suitable tools, frameworks, libraries, languages; and learn them if needed.
```

2022-02-17 13:16 UTC, stanbar commented on README.md
> +I'm currently attending to a high school in Poland, with specialization in mechatronics, although I don't assosiate my future with this profession.
```suggestion
I'm currently attending a high school in Poland with a specialization in mechatronics. But, what fascinates me the most is software development, and therefore my future is in programming.
```

2022-02-17 13:16 UTC, stanbar commented on README.md
> +- Fun fact: Back when I was 13, I created a autoclicker for Minecraft using AutoHotkey, but after the project was done, I made a 2 year break from programming.
```suggestion
> Fun fact: Back when I was 13, I created an auto clicker for Minecraft using AutoHotkey. When the project was done, I made a 2-year break from programming.
```

2022-02-20 04:10 UTC, gbaranski commented on README.md
> +I'm pretty fluent with Rust, moreover languages like Go or Typescript aren't foreign to me.
Don’t you think that using "less with ..." makes it sound as if I’m unfamiliar with Go & TS.
What do you think about “I’m fluent with Rust, and familiar with Go and Typescript too.”

2022-02-20 04:12 UTC, gbaranski commented on README.md
> +I'm fluent with Rust, less with Go and Typescript.
```suggestion
I'm fluent with Rust, and familiar with Go and Typescript too.
```

2022-02-20 04:13 UTC, gbaranski commented
thank you for your in depth review.

2022-02-20 04:13 UTC, merged

2022-02-21 09:43 UTC, stanbar commented on README.md
> +I'm pretty fluent with Rust, moreover languages like Go or Typescript aren't foreign to me.
Ok, but I would get rid of "... too" — it's redundant.